-- Drop and creat table CRM_CUST_INFO
DROP TABLE IF EXISTS BRONZE.CRM_CUST_INFO;

CREATE TABLE BRONZE.CRM_CUST_INFO (
	CST_ID INT,
	CST_KEY VARCHAR(10),
	CST_FIRSTNAME VARCHAR,
	CST_LASTNAME VARCHAR,
	CST_MARITAL_STATUS CHAR,
	CST_GNDR CHAR,
	CST_CREATE_DATE DATE
);

-- Drop and creat table CRM_PRD_INFO
DROP TABLE IF EXISTS BRONZE.CRM_PRD_INFO;

CREATE TABLE BRONZE.CRM_PRD_INFO (
	PRD_ID INT,
	PRD_KEY VARCHAR(16),
	PRD_NM VARCHAR,
	PRD_COST INT,
	PRD_LINE CHAR,
	PRD_START_DT DATE,
	PRD_END_DT DATE
);

-- Drop and creat table CRM_SALES_DETAILS
DROP TABLE IF EXISTS BRONZE.CRM_SALES_DETAILS;

CREATE TABLE BRONZE.CRM_SALES_DETAILS (
	SLS_ORD_NUM VARCHAR,
	SLS_PRD_KEY VARCHAR(10),
	SLS_CUST_ID INT,
	SLS_ORDER_DT INT,
	SLS_SHIP_DT INT,
	SLS_DUE_DT INT,
	SLS_SALES INT,
	SLS_QUANTITY INT,
	SLS_PRICE INT
);

-- Drop and creat table ERP_CUST_AZ12
DROP TABLE IF EXISTS BRONZE.ERP_CUST_AZ12;

CREATE TABLE BRONZE.ERP_CUST_AZ12 (CID VARCHAR(13), BDATE DATE, GEN VARCHAR(7));

-- Drop and creat table ERP_LOC_A101
DROP TABLE IF EXISTS BRONZE.ERP_LOC_A101;

CREATE TABLE BRONZE.ERP_LOC_A101 (CID VARCHAR(11), CNTRY VARCHAR);

-- Drop and creat table ERP_PX_CAT_G1V2
DROP TABLE IF EXISTS BRONZE.ERP_PX_CAT_G1V2;

CREATE TABLE BRONZE.ERP_PX_CAT_G1V2 (
	ID VARCHAR(5),
	CAT VARCHAR,
	SUBCAT VARCHAR,
	MAINTENANCE VARCHAR(3)
);