DROP TABLE IF EXISTS GOLD.FACT_SALES;

DROP TABLE IF EXISTS GOLD.DIM_DATE;

DROP TABLE IF EXISTS GOLD.DIM_CUSTOMER;

DROP TABLE IF EXISTS GOLD.DIM_PRODUCT;

-- Date dimension table
CREATE TABLE GOLD.DIM_DATE (
	DATE_KEY INT PRIMARY KEY,
	FULL_DATE DATE,
	YEAR_NUMBER INT,
	QUARTER_NUMBER INT,
	MOTH_NUMBER INT,
	WEEK_NUMBER INT,
	MONTH_NAME VARCHAR,
	DAY_NAME VARCHAR
);

-- Customer dimension table
CREATE TABLE GOLD.DIM_CUSTOMER (
	CUSTOMER_KEY SERIAL PRIMARY KEY,
	CUSTOMER_ID INT,
	CUSTOMER_NUMBER VARCHAR(10),
	FIRST_NAME VARCHAR,
	LAST_NAME VARCHAR,
	COUNTRY VARCHAR,
	MARITAL_STATUS VARCHAR(7),
	GENDER VARCHAR(7),
	CREATE_DATE DATE,
	BIRTH_DATE DATE
);

-- Date dimension table
CREATE TABLE GOLD.DIM_PRODUCT (
	PRODUCT_KEY SERIAL PRIMARY KEY,
	PRODUCT_ID INT,
	PRODUCT_NUMBER VARCHAR(11),
	PRODUCT_NAME VARCHAR,
	CATEGORY_ID VARCHAR(5),
	CATEGORY VARCHAR,
	SUBCATEGORY VARCHAR,
	MAINTENANCE VARCHAR(3),
	PRODUCT_COST INT,
	PRODUCT_LINE VARCHAR(11),
	START_DATE DATE
);

-- Sales fact table
CREATE TABLE GOLD.FACT_SALES (
	SALES_KEY SERIAL PRIMARY KEY,
	ORDER_NUMBER VARCHAR,
	CUSTOMER_KEY INTEGER,
	PRODUCT_KEY INTEGER,
	ORDER_DATE INTEGER,
	SHIP_DATE INTEGER,
	DUE_DATE INTEGER,
	SALES INTEGER,
	QUANTITY INTEGER,
	PRICE INTEGER,
	FOREIGN KEY (CUSTOMER_KEY) REFERENCES GOLD.DIM_CUSTOMER (CUSTOMER_KEY),
	FOREIGN KEY (PRODUCT_KEY) REFERENCES GOLD.DIM_PRODUCT (PRODUCT_KEY),
	FOREIGN KEY (ORDER_DATE) REFERENCES GOLD.DIM_DATE (DATE_KEY),
	FOREIGN KEY (SHIP_DATE) REFERENCES GOLD.DIM_DATE (DATE_KEY),
	FOREIGN KEY (DUE_DATE) REFERENCES GOLD.DIM_DATE (DATE_KEY)
);