CREATE OR REPLACE PROCEDURE GOLD.LOAD_GOLD() LANGUAGE PLPGSQL AS $$
BEGIN
-- Loading Date Dimension
TRUNCATE TABLE GOLD.DIM_DATE,
GOLD.DIM_CUSTOMER,
GOLD.DIM_PRODUCT,
GOLD.FACT_SALES;

INSERT INTO
	GOLD.DIM_DATE
SELECT
	TO_CHAR(DATES, 'YYYYMMDD')::INTEGER DATE_KEY,
	DATES FULL_DATE,
	EXTRACT(
		YEAR
		FROM
			DATES
	) YEAR_NUMBER,
	EXTRACT(
		QUARTER
		FROM
			DATES
	) QUARTER_NUMBER,
	EXTRACT(
		MONTH
		FROM
			DATES
	) MONTH_NUMBER,
	EXTRACT(
		WEEK
		FROM
			DATES
	) WEEK_NUMBER,
	TO_CHAR(DATES, 'Month') MONTH_NAME,
	TO_CHAR(DATES, 'Day') DAY_NAME
FROM
	(
		SELECT
			PRD_START_DT AS DATES
		FROM
			SILVER.CRM_PRD_INFO
		WHERE
			PRD_START_DT IS NOT NULL
		UNION
		SELECT
			PRD_END_DT AS DATES
		FROM
			SILVER.CRM_PRD_INFO
		WHERE
			PRD_END_DT IS NOT NULL
		UNION
		SELECT
			CAST(CAST(SLS_ORDER_DT AS TEXT) AS DATE)
		FROM
			SILVER.CRM_SALES_DETAILS
		WHERE
			SLS_ORDER_DT IS NOT NULL
		UNION
		SELECT
			CAST(CAST(SLS_SHIP_DT AS TEXT) AS DATE)
		FROM
			SILVER.CRM_SALES_DETAILS
		WHERE
			SLS_SHIP_DT IS NOT NULL
		UNION
		SELECT
			CAST(CAST(SLS_DUE_DT AS TEXT) AS DATE)
		FROM
			SILVER.CRM_SALES_DETAILS
		WHERE
			SLS_DUE_DT IS NOT NULL
		UNION
		SELECT
			BDATE
		FROM
			SILVER.ERP_CUST_AZ12
		WHERE
			BDATE IS NOT NULL
		ORDER BY
			DATES
	);

-- Loading Customer Dimension
INSERT INTO
	GOLD.DIM_CUSTOMER (
		CUSTOMER_ID,
		CUSTOMER_NUMBER,
		FIRST_NAME,
		LAST_NAME,
		COUNTRY,
		MARITAL_STATUS,
		GENDER,
		CREATE_DATE,
		BIRTH_DATE
	)
SELECT
	CRM_INFO.CST_ID AS CUSTOMER_ID,
	CRM_INFO.CST_KEY AS CUSTOMER_NUMBER,
	CRM_INFO.CST_FIRSTNAME AS FIRST_NAME,
	CRM_INFO.CST_LASTNAME AS LAST_NAME,
	ERP_LOC.CNTRY AS COUNTRY,
	CRM_INFO.CST_MARITAL_STATUS AS MARITAL_STATUS,
	CASE
		WHEN ERP_INFO.GEN = 'n/a'
		OR ERP_INFO.GEN IS NULL THEN CRM_INFO.CST_GNDR
		WHEN CRM_INFO.CST_GNDR = 'n/a' THEN ERP_INFO.GEN
		ELSE CRM_INFO.CST_GNDR
	END AS GENDER,
	CRM_INFO.CST_CREATE_DATE AS CREATE_DATE,
	ERP_INFO.BDATE AS BIRTH_DATE
FROM
	SILVER.CRM_CUST_INFO CRM_INFO
	LEFT JOIN SILVER.ERP_CUST_AZ12 ERP_INFO ON CRM_INFO.CST_KEY = SUBSTRING(ERP_INFO.CID, 4)
	LEFT JOIN SILVER.ERP_LOC_A101 ERP_LOC ON CRM_INFO.CST_KEY = ERP_LOC.CID
ORDER BY
	CUSTOMER_ID;

-- Loading Product Dimension
INSERT INTO
	GOLD.DIM_PRODUCT (
		PRODUCT_ID,
		PRODUCT_NUMBER,
		PRODUCT_NAME,
		CATEGORY_ID,
		CATEGORY,
		SUBCATEGORY,
		MAINTENANCE,
		PRODUCT_COST,
		PRODUCT_LINE,
		START_DATE
	)
SELECT
	PRD_ID AS PRODUCT_ID,
	PRD_KEY AS PRODUCT_NUMBER,
	PRD_NM AS PRODUCT_NAME,
	CAT_ID AS CATEGORY_ID,
	CAT AS CATEGORY,
	SUBCAT AS SUBCATEGORY,
	MAINTENANCE,
	PRD_COST AS PRODUCT_COST,
	PRD_LINE AS PRODUCT_LINE,
	PRD_START_DT AS START_DATE
FROM
	SILVER.CRM_PRD_INFO CRM
	LEFT JOIN SILVER.ERP_PX_CAT_G1V2 ERP ON CRM.CAT_ID = ERP.ID
WHERE
	PRD_END_DT IS NULL
ORDER BY
	PRODUCT_ID;

-- Loading sales fact table
INSERT INTO
	GOLD.FACT_SALES (
		ORDER_NUMBER,
		CUSTOMER_KEY,
		PRODUCT_KEY,
		ORDER_DATE,
		SHIP_DATE,
		DUE_DATE,
		SALES,
		QUANTITY,
		PRICE
	)
SELECT
	SLS_ORD_NUM AS ORDER_NUMBER,
	CUSTOMER_KEY,
	PRODUCT_KEY,
	SLS_ORDER_DT AS ORDER_DATE,
	SLS_SHIP_DT AS SHIP_DATE,
	SLS_DUE_DT AS DUE_DATE,
	SLS_SALES AS SALES,
	SLS_QUANTITY AS QUANTITY,
	SLS_PRICE AS PRICE
FROM
	SILVER.CRM_SALES_DETAILS
	JOIN GOLD.DIM_PRODUCT ON SLS_PRD_KEY = PRODUCT_NUMBER
	JOIN GOLD.DIM_CUSTOMER ON SLS_CUST_ID = CUSTOMER_ID;
END $$;