-- Drop and creat table CRM_CUST_INFO
DROP TABLE IF EXISTS SILVER.CRM_CUST_INFO;

CREATE TABLE SILVER.CRM_CUST_INFO (
	CST_ID INT,
	CST_KEY VARCHAR(10),
	CST_FIRSTNAME VARCHAR,
	CST_LASTNAME VARCHAR,
	CST_MARITAL_STATUS VARCHAR(7),
	CST_GNDR VARCHAR(7),
	CST_CREATE_DATE DATE,
	DWH_LOAD_DATE TIMESTAMP DEFAULT LOCALTIMESTAMP
);

-- Drop and creat table CRM_PRD_INFO
DROP TABLE IF EXISTS SILVER.CRM_PRD_INFO;

CREATE TABLE SILVER.CRM_PRD_INFO (
	PRD_ID INT,
	CAT_ID VARCHAR(5),
	PRD_KEY VARCHAR(11),
	PRD_NM VARCHAR,
	PRD_COST INT,
	PRD_LINE VARCHAR(11),
	PRD_START_DT DATE,
	PRD_END_DT DATE,
	DWH_LOAD_DATE TIMESTAMP DEFAULT LOCALTIMESTAMP
);

-- Drop and creat table CRM_SALES_DETAILS
DROP TABLE IF EXISTS SILVER.CRM_SALES_DETAILS;

CREATE TABLE SILVER.CRM_SALES_DETAILS (
	SLS_ORD_NUM VARCHAR,
	SLS_PRD_KEY VARCHAR(10),
	SLS_CUST_ID INT,
	SLS_ORDER_DT DATE,
	SLS_SHIP_DT DATE,
	SLS_DUE_DT DATE,
	SLS_SALES INT,
	SLS_QUANTITY INT,
	SLS_PRICE INT,
	DWH_LOAD_DATE TIMESTAMP DEFAULT LOCALTIMESTAMP
);

-- Drop and creat table ERP_CUST_AZ12
DROP TABLE IF EXISTS SILVER.ERP_CUST_AZ12;

CREATE TABLE SILVER.ERP_CUST_AZ12 (
	CID VARCHAR(13),
	BDATE DATE,
	GEN VARCHAR(7),
	DWH_LOAD_DATE TIMESTAMP DEFAULT LOCALTIMESTAMP
);

-- Drop and creat table LOC_A101
DROP TABLE IF EXISTS SILVER.ERP_LOC_A101;

CREATE TABLE SILVER.ERP_LOC_A101 (
	CID VARCHAR(11),
	CNTRY VARCHAR,
	DWH_LOAD_DATE TIMESTAMP DEFAULT LOCALTIMESTAMP
);

-- Drop and creat table ERP_PX_CAT_G1V2
DROP TABLE IF EXISTS SILVER.ERP_PX_CAT_G1V2;

CREATE TABLE SILVER.ERP_PX_CAT_G1V2 (
	ID VARCHAR(5),
	CAT VARCHAR,
	SUBCAT VARCHAR,
	MAINTENANCE VARCHAR(3),
	DWH_LOAD_DATE TIMESTAMP DEFAULT LOCALTIMESTAMP
);